### ISSUE TITLE
Error on execution- Requires assistance

### ISSUE THREAD

**Issue by nikismask** [c64-dev/Cozmo.AI#5]
Getting multiple errors. What would be the issue with my setup

What's your name please?
2020-12-21 19:21:44,946 cozmo.general INFO     Shutting down connection
2020-12-21 19:21:44,946 cozmo.general INFO     Android serial=EY6TIJ5SZ5DIZSFE disconnected.
Traceback (most recent call last):
  File "C:\Users\Nikhil\Downloads\cozmo\Cozmo.AI\main.py", line 855, in <module>
    initCozmo()
  File "C:\Users\Nikhil\Downloads\cozmo\Cozmo.AI\main.py", line 106, in initCozmo
    cozmo.run_program(wake_up)
  File "C:\Users\Nikhil\AppData\Roaming\Python\Python37\site-packages\cozmo\run.py", line 849, in run_program
    connect(wrapper, conn_factory=conn_factory, connector=connector)
  File "C:\Users\Nikhil\AppData\Roaming\Python\Python37\site-packages\cozmo\run.py", line 605, in connect
    return _connect_sync(f, conn_factory, connector)
  File "C:\Users\Nikhil\AppData\Roaming\Python\Python37\site-packages\cozmo\run.py", line 530, in _connect_sync
    f(base._SyncProxy(coz_conn))
  File "C:\Users\Nikhil\AppData\Roaming\Python\Python37\site-packages\cozmo\run.py", line 835, in wrapper
    f(robot)
  File "C:\Users\Nikhil\Downloads\cozmo\Cozmo.AI\main.py", line 519, in wake_up
    ask_name(robot)
  File "C:\Users\Nikhil\Downloads\cozmo\Cozmo.AI\main.py", line 612, in ask_name
    with microphone as source:
  File "C:\Users\Nikhil\AppData\Local\Programs\Python\Python37\lib\site-packages\speech_recognition\__init__.py", line 141, in __enter__
    input=True,  # stream is an input stream
  File "C:\Users\Nikhil\AppData\Local\Programs\Python\Python37\lib\site-packages\pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Users\Nikhil\AppData\Local\Programs\Python\Python37\lib\site-packages\pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels

**Comment by c64-dev** [comment]
Hi, 
It looks like Python cannot initialize your computer's microphone. When the program asks for your name it waits and listens to user input. Can you verify that this is working ok? 
Have you installed all the relevant Python libraries regarding audio recognition?

**Comment by nikismask** [comment]
> Hi,
> It looks like Python cannot initialize your computer's microphone. When the program asks for your name it waits and listens to user input. Can you verify that this is working ok?
> Have you installed all the relevant Python libraries regarding audio recognition?

Yes.. thanks. Could figure out that default index for my microphone had the value '1' and in the code it was '2' correcting that helped out. Thanks very much for this awsome project
